In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Population_Clean = pd.read_excel('/content/4_6007878812891618215.xlsx')
Population_Clean.head()

,Date,Country,City,PlaceName,Houses,Members,Male,Female,Room,Flat,House,Tent
0,2017-01-29,Iraq,Afak,تجمع الفلاحين,158,14036,3722,10314,47.0,79.0,32.0,NaN
1,2017-01-29,Iraq,Afak,تجمع الفلاحين,81,1537,805,732,24.0,41.0,16.0,NaN
2,2017-01-29,Lybia,Bayda,أول طلعة الأوسطى,84,2864,992,1872,25.0,42.0,17.0,NaN
3,2017-01-29,Lybia,Marj,سبلبات,82,3652,1559,2093,25.0,41.0,16.0,NaN
4,2017-01-29,Syria,Atma,تجمع باب الهوى,131,4505,2895,1610,39.0,66.0,26.0,NaN

In [ ]:
Population_Clean["Date"] = pd.to_datetime(Population_Clean["Date"])

Population_Clean[["Country", "City", "PlaceName"]] = \
    Population_Clean[["Country", "City", "PlaceName"]].astype(str)
Population_Clean[["Members", "Male", "Female", "Room", "Flat", "House", "Tent"]] = \
    Population_Clean[["Members", "Male", "Female", "Room", "Flat", "House", "Tent"]].astype("Int64")

In [ ]:
Population_Clean["Country"] = Population_Clean["Country"].str.strip()
Population_Clean["City"] = Population_Clean["City"].str.strip()
Population_Clean["PlaceName"] = Population_Clean["PlaceName"].str.strip()

In [ ]:
housing_cols = ['Room', 'Flat', 'House', 'Tent']
Population_Clean[housing_cols] = Population_Clean[housing_cols].fillna(0)

In [ ]:
Population_Clean = Population_Clean.dropna(how='all')
Population_Clean.duplicated().sum()
Population_Clean = Population_Clean.drop_duplicates()

In [ ]:
#12
Population_Clean["Gender_Validation"] = "Review"

Population_Clean.loc[
    Population_Clean["Members"] == Population_Clean["Male"] + Population_Clean["Female"],
    "Gender_Validation"
] = "OK"
Population_Clean[["Members", "Male", "Female", "Gender_Validation"]].head()

   Members  Male  Female Gender_Validation
0    14036  3722   10314                OK
1     1537   805     732                OK
2     2864   992    1872                OK
3     3652  1559    2093                OK
4     4505  2895    1610                OK

In [ ]:
#13
Population_Clean["Date"] = pd.to_datetime(Population_Clean["Date"])

Population_Clean["Year"] = Population_Clean["Date"].dt.year
Population_Clean["Month"] = Population_Clean["Date"].dt.month
Population_Clean[["Date", "Year", "Month"]].head()

        Date  Year  Month
0 2017-01-29  2017      1
1 2017-01-29  2017      1
2 2017-01-29  2017      1
3 2017-01-29  2017      1
4 2017-01-29  2017      1

In [ ]:
Population_Clean.to_excel("population_cleaned.xlsx", index=False)
from google.colab import files

files.download("population_cleaned.xlsx")